# Site settings
title: Chowdown
email: correuperamerda@hotmail.com
description: The plain text recipe database for hackers
baseurl: "https://github.com/lamevacuina/chowdown/"
github_username:  lamevacuina

# Build settings
markdown: kramdown

permalink: /:title:output_ext

collections:
  components:
    output: true
  recipes:
    output: true

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
